image: "python:3.7"

before_script:
  - pip install '.[dev]'

stages:
  - test

test:
  stage: test
  script:
    - pytest --doctest-modules src/ tests/ --cov=src/ --cov-config=setup.cfg

lint:
  stage: test
  script:
    - flake8 src/